/**
 * 店赢OS - 渠道增长/客服/产品/安全/系统模块
 */
function renderChannelAnalysisPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">渠道分析</h1><p class="page-subtitle">获客渠道效果分析</p></div></div><div class="table-container"><table><thead><tr><th>渠道</th><th>线索数</th><th>转化数</th><th>转化率</th><th>成本</th></tr></thead><tbody><tr><td>线下沙龙</td><td>320</td><td>86</td><td>26.9%</td><td>¥45,000</td></tr><tr><td>转介绍</td><td>180</td><td>72</td><td class="text-success">40.0%</td><td>¥28,000</td></tr></tbody></table></div>`; }
function renderInviteFissionPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">邀请裂变</h1><p class="page-subtitle">裂变活动数据</p></div></div><div class="stats-grid mb-6"><div class="stat-card"><div class="stat-icon primary"><i data-lucide="users"></i></div><div class="stat-content"><div class="stat-label">总邀请数</div><div class="stat-value">856</div></div></div><div class="stat-card"><div class="stat-icon success"><i data-lucide="check-circle"></i></div><div class="stat-content"><div class="stat-label">成功邀请</div><div class="stat-value">324</div></div></div></div>`; }
function renderTrialPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">试用管理</h1><p class="page-subtitle">试用商家管理</p></div></div><div class="stats-grid mb-6"><div class="stat-card"><div class="stat-content"><div class="stat-label">试用总数</div><div class="stat-value">128</div></div></div><div class="stat-card"><div class="stat-content"><div class="stat-label">转化率</div><div class="stat-value text-success">48.4%</div></div></div></div>`; }
function renderPartnersPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">合作伙伴</h1><p class="page-subtitle">合作企业管理</p></div></div><div class="table-container"><table><thead><tr><th>伙伴名称</th><th>类型</th><th>状态</th><th>合作时间</th></tr></thead><tbody><tr><td>招商银行</td><td>银行</td><td><span class="badge badge-success">合作中</span></td><td>2024-01</td></tr></tbody></table></div>`; }
function renderTicketsPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">工单系统</h1><p class="page-subtitle">客服工单管理</p></div></div><div class="table-container"><table><thead><tr><th>工单号</th><th>商家</th><th>类型</th><th>标题</th><th>状态</th><th>优先级</th><th>操作</th></tr></thead><tbody>${App.data.tickets.map(t=>`<tr><td class="font-mono">${t.id}</td><td>${t.merchant}</td><td>${t.type}</td><td>${t.title}</td><td><span class="badge badge-${Utils.getStatusClass(t.status)}">${Utils.getStatusLabel(t.status)}</span></td><td><span class="badge badge-${t.priority==='high'?'danger':t.priority==='medium'?'warning':'gray'}">${t.priority}</span></td><td><button class="btn btn-ghost btn-sm">处理</button></td></tr>`).join('')}</tbody></table></div>`; }
function renderFAQPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">FAQ管理</h1><p class="page-subtitle">常见问题管理</p></div></div><div class="card"><div class="card-header"><h3 class="card-title">问题列表</h3></div><div class="faq-list"><div class="faq-item"><div class="faq-q">Q: 如何开通AI客服功能？</div><div class="faq-a">A: 进入商家后台 > AI助手 > 开启智能客服即可</div></div></div></div>`; }
function renderSatisfactionPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">满意度调研</h1><p class="page-subtitle">客户满意度数据</p></div></div><div class="stats-grid mb-6"><div class="stat-card"><div class="stat-icon success"><i data-lucide="smile"></i></div><div class="stat-content"><div class="stat-label">NPS评分</div><div class="stat-value">72</div></div></div></div>`; }
function renderFeatureFlagsPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">功能开关</h1><p class="page-subtitle">功能配置管理</p></div></div><div class="card"><div class="card-header"><h3 class="card-title">功能列表</h3></div><div class="permission-list"><div class="permission-item"><div class="permission-info"><div class="permission-name">AI对话2.0</div></div><label class="switch"><input type="checkbox" checked><span class="switch-slider"></span></label></div></div></div>`; }
function renderABTestPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">AB测试</h1><p class="page-subtitle">实验管理</p></div></div><div class="card"><div class="card-header"><h3 class="card-title">进行中的实验</h3></div><div class="text-muted">暂无进行中的实验</div></div>`; }
function renderRequirementsPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">需求池</h1><p class="page-subtitle">客户需求管理</p></div></div><div class="table-container"><table><thead><tr><th>需求</th><th>提出商家</th><th>投票数</th><th>状态</th></tr></thead><tbody><tr><td>增加批量导入功能</td><td>北京湘菜馆</td><td>45</td><td><span class="badge badge-warning">开发中</span></td></tr></tbody></table></div>`; }
function renderVersionManagementPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">版本管理</h1><p class="page-subtitle">系统版本发布</p></div></div><div class="table-container"><table><thead><tr><th>版本</th><th>状态</th><th>发布时间</th><th>更新内容</th></tr></thead><tbody><tr><td class="font-mono">V3.0.0</td><td><span class="badge badge-success">已上线</span></td><td>2024-12-01</td><td>全新UI设计，AI能力升级</td></tr></tbody></table></div>`; }
function renderLoginSecurityPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">登录安全</h1><p class="page-subtitle">账户安全监控</p></div></div><div class="card"><div class="card-header"><h3 class="card-title">登录日志</h3></div><div class="table-container"><table><thead><tr><th>用户</th><th>类型</th><th>地点</th><th>时间</th><th>状态</th></tr></thead><tbody><tr><td>张管理员</td><td>正常登录</td><td>北京市</td><td>2024-12-03</td><td><span class="badge badge-success">成功</span></td></tr></tbody></table></div></div>`; }
function renderDataMaskingPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">数据脱敏</h1><p class="page-subtitle">敏感数据保护</p></div></div><div class="card"><div class="card-header"><h3 class="card-title">脱敏规则</h3></div><table><thead><tr><th>数据类型</th><th>规则</th><th>状态</th></tr></thead><tbody><tr><td>手机号</td><td>138****8001</td><td><span class="badge badge-success">已启用</span></td></tr></tbody></table></div>`; }
function renderCompliancePage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">合规审计</h1><p class="page-subtitle">合规审计日志</p></div></div><div class="card"><div class="card-header"><h3 class="card-title">审计日志</h3></div><div class="text-muted">暂无审计记录</div></div>`; }
function renderRolesPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">角色权限</h1><p class="page-subtitle">管理员角色配置</p></div><div class="page-actions"><button class="btn btn-primary"><i data-lucide="plus"></i> 新增角色</button></div></div><div class="table-container"><table><thead><tr><th>角色名称</th><th>权限数</th><th>用户数</th><th>操作</th></tr></thead><tbody><tr><td class="font-medium">超级管理员</td><td>全部</td><td>2</td><td><button class="btn btn-ghost btn-sm"><i data-lucide="edit-2"></i></button></td></tr></tbody></table></div>`; }
function renderOperationLogsPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">操作日志</h1><p class="page-subtitle">管理员操作记录</p></div></div><div class="table-container"><table><thead><tr><th>操作人</th><th>类型</th><th>对象</th><th>操作</th><th>时间</th></tr></thead><tbody><tr><td>张管理员</td><td>商家管理</td><td>北京湘菜馆</td><td>开通旗舰版</td><td>2024-12-01</td></tr></tbody></table></div>`; }
function renderPricingPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">定价配置</h1><p class="page-subtitle">版本价格管理</p></div></div><div class="grid-3">${[{name:'免费版',price:0,features:['基础功能']},{name:'专业版',price:980,features:['完整AI套件']},{name:'旗舰版',price:2980,features:['全部AI能力']}].map(p=>`<div class="price-card ${p.name==='旗舰版'?'featured':''}"><h3 class="font-bold">${p.name}</h3><div class="price-amount">¥${p.price}</div><ul class="price-features">${p.features.map(f=>`<li><i data-lucide="check"></i> ${f}</li>`).join('')}</ul></div>`).join('')}</div>`; }
function renderNotificationsPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">消息通知</h1><p class="page-subtitle">通知渠道配置</p></div></div><div class="card"><div class="card-header"><h3 class="card-title">通知开关</h3></div><div class="permission-list"><div class="permission-item"><div class="permission-info"><div class="permission-name">邮件通知</div></div><label class="switch"><input type="checkbox" checked><span class="switch-slider"></span></label></div></div></div>`; }
