/**
 * 店赢OS - 支付交易模块
 */
function renderPaymentChannelsPage(container) {
  const channels = [
    { name: '微信支付', status: 'online', successRate: 99.2, avgTime: 120, todayVolume: 856000 },
    { name: '支付宝', status: 'online', successRate: 98.8, avgTime: 135, todayVolume: 728000 },
    { name: '银联支付', status: 'online', successRate: 97.5, avgTime: 180, todayVolume: 245000 },
    { name: '信用卡', status: 'degraded', successRate: 92.3, avgTime: 280, todayVolume: 126000 }
  ];
  container.innerHTML += `<div class="page-header"><div><h1 class="page-title">支付通道监控</h1><p class="page-subtitle">各通道状态和成功率</p></div></div><div class="stats-grid mb-6"><div class="stat-card"><div class="stat-icon success"><i data-lucide="check-circle"></i></div><div class="stat-content"><div class="stat-label">总体成功率</div><div class="stat-value">98.5%</div></div></div><div class="stat-card"><div class="stat-icon primary"><i data-lucide="activity"></i></div><div class="stat-content"><div class="stat-label">今日交易量</div><div class="stat-value">¥195.5万</div></div></div></div><div class="table-container"><table><thead><tr><th>通道</th><th>状态</th><th>成功率</th><th>平均耗时</th><th>今日交易额</th></tr></thead><tbody>${channels.map(p=>`<tr><td class="font-medium">${p.name}</td><td><span class="status-indicator"><span class="status-dot ${p.status}"></span><span class="badge badge-${Utils.getStatusClass(p.status)}">${Utils.getStatusLabel(p.status)}</span></span></td><td class="${p.successRate<95?'text-danger':'text-success'}">${p.successRate}%</td><td>${p.avgTime}ms</td><td>¥${(p.todayVolume/10000).toFixed(1)}万</td></tr>`).join('')}</tbody></table></div>`;
}
function renderTransactionsPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">交易流水</h1><p class="page-subtitle">全平台交易明细</p></div></div><div class="table-container"><table><thead><tr><th>流水号</th><th>商家</th><th>金额</th><th>类型</th><th>状态</th><th>时间</th></tr></thead><tbody>${App.data.transactions.map(t=>`<tr><td class="font-mono text-sm">${t.id}</td><td>${t.merchant}</td><td class="${t.status==='success'?'text-success':'text-muted'}">¥${t.amount}</td><td><span class="tag">${t.type}</span></td><td><span class="badge badge-${Utils.getStatusClass(t.status)}">${Utils.getStatusLabel(t.status)}</span></td><td>${t.time}</td></tr>`).join('')}</tbody></table></div>`; }
function renderFeeConfigPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">费率配置</h1><p class="page-subtitle">配置各类型交易费率</p></div><div class="page-actions"><button class="btn btn-primary"><i data-lucide="save"></i> 保存</button></div></div><div class="card mb-6"><div class="card-header"><h3 class="card-title">按行业费率</h3></div><table><thead><tr><th>行业</th><th>费率</th><th>操作</th></tr></thead><tbody><tr><td>餐饮</td><td>0.6%</td><td><button class="btn btn-ghost btn-sm"><i data-lucide="edit"></i></button></td></tr></tbody></table></div>`; }
function renderSplitPaymentPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">分账管理</h1><p class="page-subtitle">平台与代理商分账规则</p></div></div><div class="card mb-6"><div class="card-header"><h3 class="card-title">分账规则</h3></div><div class="flex gap-6 p-4" style="background:var(--bg);border-radius:8px"><div class="text-center flex-1"><div class="text-3xl font-bold text-primary">70%</div><div class="text-sm text-muted">商家所得</div></div><div class="text-center flex-1"><div class="text-3xl font-bold text-accent">20%</div><div class="text-sm text-muted">平台所得</div></div><div class="text-center flex-1"><div class="text-3xl font-bold text-warning">10%</div><div class="text-sm text-muted">代理商</div></div></div></div>`; }
function renderReconciliationPage(container) { container.innerHTML += `<div class="page-header"><div><h1 class="page-title">对账中心</h1><p class="page-subtitle">自动对账和差异处理</p></div></div><div class="stats-grid mb-6"><div class="stat-card"><div class="stat-icon success"><i data-lucide="check-circle"></i></div><div class="stat-content"><div class="stat-label">已对账</div><div class="stat-value">1,856</div></div></div><div class="stat-card"><div class="stat-icon warning"><i data-lucide="alert-circle"></i></div><div class="stat-content"><div class="stat-label">差异</div><div class="stat-value">3</div></div></div></div>`; }
